[package]
name = "styx-cyclonev-processor"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
styx-core = { workspace = true }
styx-gic = { path = "../../../event-controllers/arm/styx-gic" }
styx-cyclone-v-hps-sys = { path = "../../../generated/styx-cyclone-v-hps-sys", features = [
  "uart0",
  "uart1",
  "sdmmc",
  "clkmgr",
] }
styx-peripherals = { path = "../../../peripherals" }

arbitrary-int = { workspace = true }
async-trait = { workspace = true }
derivative = { workspace = true }
embed-doc-image = { workspace = true }
paste = { workspace = true }
thiserror = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

[dev-dependencies]
styx-plugins = { path = "../../../plugins" }

[features]
default = []
tracy = ["styx-plugins/tracy"]

[package.metadata.cargo-udeps.ignore]
development = ["styx-plugins"]
