[package]
name = "styx-aarch64-processor"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
styx-core = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

[dev-dependencies]
test-case = { workspace = true }
