
# taplo config for toml files
# also see vscode extension: tamasfe.even-better-toml
# Config file reference:
#    - https://taplo.tamasfe.dev/configuration/file.html
# Settings reference:
#    - https://taplo.tamasfe.dev/configuration/formatter-options.html

exclude = ["*/**/pyproject.toml", "styx/workspace-hack/Cargo.toml"]

[formatting]
# Align entries vertically. Entries that have table headers, comments, or blank lines between them are not aligned.
align_entries = false

# Align consecutive comments after entries and items vertically.
# This applies to comments that are after entries or array items.
align_comments = true

# Put trailing commas for multiline arrays.
array_trailing_comma = true

# Automatically expand arrays to multiple lines when they exceed column_width characters.
array_auto_expand = true

# Automatically collapse arrays if they fit in one line.
array_auto_collapse = true

# Omit whitespace padding inside single-line arrays.
compact_arrays = true

# Omit whitespace padding inside inline tables.
compact_inline_tables = false

# Expand values (e.g. arrays) inside inline tables.
inline_table_expand = true

# Omit whitespace around =.
compact_entries = false

# Target maximum column width after which arrays are expanded into new lines.
column_width = 80

# Indent subtables if they come in order.
indent_tables = false

# Indent entries under tables.
indent_entries = false

# Indentation to use, should be tabs or spaces but technically could be anything.
indent_string = "  "

# Add trailing newline to the source.
trailing_newline = true

# Alphabetically reorder keys that are not separated by blank lines.
reorder_keys = false

# Alphabetically reorder array values that are not separated by blank lines.
reorder_arrays = false

# The maximum amount of consecutive blank lines allowed.
allowed_blank_lines = 2

# Use CRLF line endings.
crlf = false
