[package]
name = "styx-pcode-sleigh-backend"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
styx-pcode = { path = "../styx-pcode" }
styx-sleigh-bindings = { package = "styx-sleigh-bindings", path = "../styx-sleigh-bindings" }
styx-cpu-type = { path = "../../styx-cpu-type" }
styx-sync = { path = "../../styx-sync" }
cxx = { workspace = true }
thiserror = { workspace = true }
num = { workspace = true }
vector-map = { workspace = true }
smallvec = { workspace = true }
styx-util = { path = "../../styx-util" }
styx-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
