
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1 EDK_K.15
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved.
*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xuartlite.h"

/*
* The configuration table for devices
*/

XUartLite_Config XUartLite_ConfigTable[] =
{
	{
		XPAR_RS232_UART_DEVICE_ID,
		XPAR_RS232_UART_BASEADDR,
		XPAR_RS232_UART_BAUDRATE,
		XPAR_RS232_UART_USE_PARITY,
		XPAR_RS232_UART_ODD_PARITY,
		XPAR_RS232_UART_DATA_BITS
	}
};
