// SPDX-License-Identifier: BSD-2-Clause
use crate::StyxMachineError;
use crate::UnknownError;
use styx_cpu_type::{arch::backends::ArchVariant, ArchEndian};

/// Generated by `ProcessorBuilder`.
#[derive(Debug, thiserror::Error)]
pub enum ProcessorBuilderError {
    #[error("Requested backend not supported")]
    BackendNotSupported,
    #[error("Backend not provided")]
    BackendRequired,
    #[error("Requested cpu variant not supported")]
    CpuVariantNotSupported,
    #[error("endianness {0} not supported")]
    EndianNotSupported(ArchEndian),
    #[error("No endian provided")]
    NoEndian,
    #[error("No Executor plugin")]
    NoExecutor,
    #[error("No loader provided")]
    NoLoader,
    #[error("No path to guest code provided")]
    NoTargetProgram,
    #[error("No cpu variant provided")]
    NoVariant,
    #[error(transparent)]
    Unknown(#[from] UnknownError),
}

impl From<ProcessorBuilderError> for StyxMachineError {
    fn from(value: ProcessorBuilderError) -> Self {
        Self::ProcessorBuilder(value)
    }
}

/// Generated by `BuildableProcessor`.
#[derive(Debug, thiserror::Error)]
pub enum ProcessorBuilderImplError {
    #[error("Requested backend not supported")]
    BackendNotSupported,
    #[error("Requested cpu variant not supported")]
    CpuVariantNotSupported,
    #[error("endianness {0} not supported")]
    EndianNotSupported(ArchEndian),
    #[error("Family Conversion Incompatibility: From: `{0:?}`")]
    FamilyIncompatibility(ArchVariant),
    #[error(transparent)]
    Unknown(#[from] UnknownError),
}

impl From<ProcessorBuilderImplError> for ProcessorBuilderError {
    fn from(value: ProcessorBuilderImplError) -> Self {
        match value {
            ProcessorBuilderImplError::BackendNotSupported => {
                ProcessorBuilderError::BackendNotSupported
            }
            ProcessorBuilderImplError::CpuVariantNotSupported => {
                ProcessorBuilderError::CpuVariantNotSupported
            }
            ProcessorBuilderImplError::EndianNotSupported(endian) => {
                ProcessorBuilderError::EndianNotSupported(endian)
            }
            err @ ProcessorBuilderImplError::FamilyIncompatibility(_) => {
                anyhow::anyhow!(err).into()
            }
            err @ ProcessorBuilderImplError::Unknown(_) => anyhow::anyhow!(err).into(),
        }
    }
}

#[derive(thiserror::Error, Debug)]
pub enum StartProcessorError {
    #[error("processor already running")]
    ProcessorRunning,
    #[error(transparent)]
    Unknown(#[from] UnknownError),
}

#[derive(thiserror::Error, Debug)]
pub enum PauseProcessorError {
    #[error("processor already paused")]
    ProcessorPaused,
    #[error(transparent)]
    Unknown(#[from] UnknownError),
}
