[package]
name = "styx-c-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = ["unicorn-backend"]
unicorn-backend = ["styx-emulator/unicorn-backend"]

[dependencies]
styx-emulator = { path = "../.." }

# these are all beholden to styx
bitflags = { version = "*" }
paste = { version = "*" }
arbitrary-int = { version = "*" }

[build-dependencies]
cbindgen = "0.29.0"
