language = "C"

after_includes = """
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"

#ifndef u128
typedef unsigned __int128 u128;
#endif /* u128 */

#ifndef i128
typedef __int128 i128;
#endif /* i128 */

/* This tracks `styx_core::memory::MemoryPermissions`
 * XXX: add `styx_core::memory` to get exported by the bindings
 */
typedef uint32_t Internal;
"""

trailer = """
#pragma GCC diagnostic pop
"""

namespace = "styx_emulator::c"

[macro_expansion]
bitflags = true

[enum]
rename_variants = "QualifiedScreamingSnakeCase"

[parse.expand]
crates = ["styx-c-api"]
