[package]
name = "styx-cpu-type"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
unicorn-backend = ["dep:unicorn-engine"]

[dependencies]
styx-macros = { path = "../styx-macros" }
styx-sync = { path = "../styx-sync" }
styx-util = { path = "../styx-util" }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }

arbitrary-int = { workspace = true }
enum-as-inner = { workspace = true }
enum_dispatch = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
derive_more = { workspace = true }
gdbstub = { workspace = true }
gdbstub_arch = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
unicorn-engine = { workspace = true, optional = true }
paste = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
lazy_static = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }
