# cargo-deny configuration for nogpl checks of the nogpl build.
#
# THIS DOES NOT WORK IN ROOT REPO. Check out the nogpl-check script for how to use.
#

[graph]
all-features = false
no-default-features = true
exclude-unpublished = true

[output]
feature-depth = 1

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unicode-3.0",
  "BSL-1.0",
  "BSD-2-Clause",
  "CDLA-Permissive-2.0",
  "MPL-2.0",
  "ISC",
  "Zlib",
  "BSD-3-Clause",
  "0BSD",
]
confidence-threshold = 0.8

[[licenses.clarify]]
crate = "unicorn-engine"
expression = "GPL-2.0-only"
license-files = []

[licenses.private]
ignore = true
