# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class DefaultExecutor(StyxExecutor):
    def __new__(cls) -> tuple[DefaultExecutor, StyxExecutor]: ...

class StyxExecutor:
    ...
