# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class BlackfinLDRLoader(Loader):
    def __new__(cls) -> tuple[BlackfinLDRLoader, Loader]: ...

class ElfLoader(Loader):
    def __new__(cls) -> tuple[ElfLoader, Loader]: ...

class Loader:
    ...

class RawLoader(Loader):
    def __new__(cls) -> tuple[RawLoader, Loader]: ...
