# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

class UartClient:
    def __new__(cls, addr:str, uart_port:typing.Optional[builtins.int]=None) -> UartClient: ...
    def recv_nonblocking(self, len:builtins.int) -> typing.Optional[bytes]: ...
    def send(self, bytes:bytes) -> None: ...
