# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401


class Plugin:
    ...

class ProcessorTracingPlugin(Plugin):
    def __new__(cls) -> tuple[ProcessorTracingPlugin, Plugin]: ...
