[package]
name = "styx-macros"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
gdbstub = { workspace = true }      # for doctests
gdbstub_arch = { workspace = true } # for doctests
log = { workspace = true }          # for doctests

[package.metadata.cargo-udeps.ignore]
development = ["gdbstub", "gdbstub_arch", "log"]
