[package]
name = "styx-arch-utils"
edition.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
styx-cpu = { path = "../styx-cpu" }
styx-processor = { path = "../styx-processor" }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }
