[package]
name = "styx-stm32f405-processor"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
unicorn-backend = ["styx-core/unicorn-backend"]

[dependencies]
styx-core = { workspace = true }
styx-nvic = { path = "../../../event-controllers/arm/styx-nvic" }
styx-stm32f405-sys = { path = "../../../generated/styx-stm32f405-sys", features = [
  "usart1",
  "usart2",
  "usart3",
  "uart4",
  "uart5",
  "uart7",
  "uart8",
  "usart6",
  "dma1",
  "dma2",
  "rcc",
] }
styx-peripherals = { path = "../../../peripherals" }

tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
derivative = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
paste = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
