# apply to all invocations
# uses [target.<cfg>] to allow unification of rustflag options in other cargo configs
# see https://doc.rust-lang.org/cargo/reference/config.html#buildrustflags
# TODO change to cfg(true) after upgrade to rust 1.88
[target.'cfg(all())']
rustflags = [
  "--cfg",
  "tokio_unstable", # we always build with tokio_unstable so tracing plugins can be used w/o pain
]
# keep flags the same, avoid rebuilds
rustdocflags = ["--cfg", "tokio_unstable"]

[alias]
xtask = "run --package xtask --"

[target.xtask]
rustflags = ["-C", "opt-level=3"]
