[package]
name = "styx-trace-benchmarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
styx-trace = { path = "../../styx-trace", features = ["default"] }
log = { workspace = true }
rand = { workspace = true }
