[package]
name = "typhunix-client-bin"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true


[lib]
path = "src/typhunix-client-lib.rs"

[[bin]]
name = "typhunix-client"
path = "src/typhunix-client.rs"

[dependencies]
typhunix-proto = { path = "../typhunix-proto", features = [] }
typhunix-config = { workspace = true }
styx-emulator = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
futures = { workspace = true }
futures-lite = { workspace = true }
async-fs = { workspace = true }
glob = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true, features = ["log", "async-await"] }
styx-workspace-hack = { version = "0.1", path = "../../../../styx/workspace-hack" }
