[package]
name = "styx-processor-type"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = { workspace = true }
derive_more = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
test-case = { workspace = true }

[target.'cfg(serde)'.dependencies]
serde = { workspace = true }

[features]
serde = []
