[package]
name = "styx-cpu-unicorn-backend"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
styx-memory = { path = "../styx-memory" }
styx-sync = { path = "../styx-sync" }
styx-macros = { path = "../styx-macros" }
styx-util = { path = "../styx-util" }
styx-errors = { path = "../styx-errors" }
styx-cpu-type = { path = "../styx-cpu-type" }
styx-processor = { path = "../styx-processor" }

log = { workspace = true }
tap = { workspace = true }
thiserror = { workspace = true }
unicorn-engine = { workspace = true }
derivative = { workspace = true }
arbitrary-int = { workspace = true }
ref-cast = { workspace = true }
beau_collector = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
keystone-engine = { workspace = true }

[lints]
workspace = true
