[package]
name = "styx-kinetis21-processor"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
styx-core = { workspace = true }
styx-nvic = { path = "../../../event-controllers/arm/styx-nvic" }

styx-mk21f12-sys = { path = "../../../generated/styx-mk21f12-sys" }
styx-peripherals = { path = "../../../peripherals" }

async-trait = { workspace = true }
bilge = { workspace = true }
derivative = { workspace = true }
derive_more = { workspace = true }
getset = { workspace = true }
paste = { workspace = true }
tonic = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-timerfd = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }
embed-doc-image = { workspace = true }                                      # docs
styx-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }

# needed to render pictures in documentation until
# https://github.com/rust-lang/rust/issues/32104 is resolved
[features]
docimages = []
tracy = ["styx-plugins/tracy"]
unicorn-backend = ["styx-core/unicorn-backend"]

[dev-dependencies]
styx-plugins = { path = "../../../plugins" }
keystone-engine = { workspace = true }
styx-integration-tests = { path = "../../../integration-tests" }
gdbmi = { workspace = true }                                     # required for gdb integration tests

[package.metadata.cargo-udeps.ignore]
normal = ["embed-doc-image"]
development = ["styx-plugins"]
