[package]
name = "styx-mpc866m"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
styx-core = { workspace = true }

async-trait = { workspace = true }
derive_more = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
