
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1 EDK_K.15
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved.
*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xmpmc.h"

/*
* The configuration table for devices
*/

XMpmc_Config XMpmc_ConfigTable[] =
{
	{
		XPAR_DDR_SDRAM_DEVICE_ID,
		XPAR_DDR_SDRAM_MPMC_CTRL_BASEADDR,
		XPAR_DDR_SDRAM_INCLUDE_ECC_SUPPORT,
		XPAR_DDR_SDRAM_USE_STATIC_PHY,
		XPAR_DDR_SDRAM_PM_ENABLE
	}
};
