[package]
name = "macrolib"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
styx-sync = { path = "../styx-sync" }
syn = { workspace = true }
styx-workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[lints]
workspace = true
